// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB89ia-DLWn6CKwgQzeQyM10yFmWH2fVnA',
    appId: '1:467210161136:web:d04baa42abe27e9c1beb35',
    messagingSenderId: '467210161136',
    projectId: 'sport-go-app',
    authDomain: 'sport-go-app.firebaseapp.com',
    storageBucket: 'sport-go-app.appspot.com',
    measurementId: 'G-5DPM386F8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBL42T2sdAKWZ5bpkOLzTzLeFfY4zVjsw',
    appId: '1:467210161136:android:706a2498cb0024181beb35',
    messagingSenderId: '467210161136',
    projectId: 'sport-go-app',
    storageBucket: 'sport-go-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9STAVc7mRTA2jUc49kYC0fRUrWh-_1Ek',
    appId: '1:467210161136:ios:c249db1a5b74946a1beb35',
    messagingSenderId: '467210161136',
    projectId: 'sport-go-app',
    storageBucket: 'sport-go-app.appspot.com',
    iosClientId: '467210161136-3t5skk8m3kmnb6csjp9ffmo3n9rc1jm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.1.test',
  );
}
